### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ue-bose** [ue-bose/chat-space#13]
#IPアドレス
54.150.196.164

**Comment by mo1015** [comment]
植田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバーのグループ同士の間隔をあけましょう
○メンバー同士の間隔をあけましょう**
（現状、aというメンバーとtanakaというメンバーが繋がって表示されています）

<img width="759" alt="修正" src="https://user-images.githubusercontent.com/62644781/86504698-d3214980-bdf6-11ea-831d-eebcea7936f1.png">
参考カリキュラム
<img width="591" alt="サイドバー見本" src="https://user-images.githubusercontent.com/62644781/86504700-dae0ee00-bdf6-11ea-90ac-ce2a40050194.png">

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ue-bose** [comment]
修正しました

**Comment by naru6117** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項はしっかり修正できていました(^^)
新たに一点修正頂きたい箇所がございます。

### [修正箇所]
①ヘッダーとメッセージ一覧の境界にカリキュラムで指定されている#eeeeeeの色をつけましょう
↓ピンクで囲った箇所です↓
<img width="729" alt="スクリーンショット 2020-07-04 15 39 20" src="https://user-images.githubusercontent.com/49669977/86506684-b8f26600-be0c-11ea-9866-fe3fb98fb7f6.png">


### [カリキュラム内の見本画像]
![スクリーンショット 2020-06-24 16 53 15](https://user-images.githubusercontent.com/49669977/86506694-d1628080-be0c-11ea-8d24-c05c54bbf91a.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ue-bose** [comment]
度々すいません。
修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
